version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "10000:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "10050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
    - ./servers.json:/pgadmin4/servers.json
